//==============================================================================
// Copyright Jan Brzobohatý 2015.
// Distributed under the MIT License.
// (See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT)
//==============================================================================

package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 * Třída představuje chybový dialog.
 */
public class ErrorDialog extends javax.swing.JDialog {
    /************************************************************************************************
    Deklarace proměnných.
    ************************************************************************************************/
    
    /**
     * Text, který má být obsahem dialogu.
     */
    String text;
    
    /************************************************************************************************
    Deklarace konstruktorů a továrních metod.
    ************************************************************************************************/
    
    /**
     * Vytvoří dialog s daným textem.
     * @param parent okno, ke kterému má být modální
     * @param text obsah dialogu
     */
    public ErrorDialog(JFrame parent, String text) {
        super(parent, true);
        this.text = text;
        initComponents();
        buttonOK.addActionListener(new ButtonOKListener());
        setVisible(true);
    }
    
    /************************************************************************************************
    Deklarace soukromých metod.
    ************************************************************************************************/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelText = new javax.swing.JLabel();
        dolniPanel = new javax.swing.JPanel();
        buttonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/error-icon.png"))); // NOI18N
        labelText.setText(text);
        labelText.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        getContentPane().add(labelText, java.awt.BorderLayout.CENTER);

        dolniPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 10, 10));
        dolniPanel.setLayout(new java.awt.GridBagLayout());

        buttonOK.setText("OK");
        dolniPanel.add(buttonOK, new java.awt.GridBagConstraints());

        getContentPane().add(dolniPanel, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOK;
    private javax.swing.JPanel dolniPanel;
    private javax.swing.JLabel labelText;
    // End of variables declaration//GEN-END:variables

    /************************************************************************************************
    Deklarace soukromých tříd.
    ************************************************************************************************/
    
    /**
     * Listener pro tlačítko OK v error dialogu.
     */
    private class ButtonOKListener implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent e) {
            dispose();
        }
    }
}
