//==============================================================================
// Copyright Jan Brzobohatý 2015.
// Distributed under the MIT License.
// (See accompanying file LICENSE or copy at http://opensource.org/licenses/MIT)
//==============================================================================

package view;

import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 * Třída představuje formulář pro zadání jména a příjmení uživatele.
 */
class NameForm extends javax.swing.JDialog {
    /************************************************************************************************
    Deklarace konstruktorů a továrních metod.
    ************************************************************************************************/
    
    /**
     * Vytvoří nový modální dialog pro zadání jména.
     * @param parent Rodičovské okno.
     */
    NameForm(JFrame parent) {
        super(parent, true);
        initComponents();
    }

    /************************************************************************************************
    Deklarace veřejných metod.
    ************************************************************************************************/
    
    /**
     * @return křestní jméno uživatele
     */
    public String getFirstName() {
        return textFieldFirstName.getText();	
    }

    /**
     * @return příjmení uživatele
     */
    public String getSurname() {
        return textFieldSurename.getText();	
    }

    /**
     * Předvyplnění formuláře daným jménem.
     * @param firstName křestní jméno uživatele
     * @param surname příjmení uživatele
     */
    public void setName(String firstName, String surname) {
            // TODO implement me	
    }
    
    public void addButtonOKNameFormListener(ActionListener listener) {
        buttonOK.addActionListener(listener);
    }
    
    /************************************************************************************************
    Deklarace soukromých metod.
    ************************************************************************************************/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelJmeno = new javax.swing.JLabel();
        labelPrijmeni = new javax.swing.JLabel();
        textFieldSurename = new javax.swing.JTextField();
        textFieldFirstName = new javax.swing.JTextField();
        buttonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Zadejte svoje jméno");
        setResizable(false);

        labelJmeno.setText("Jméno:");

        labelPrijmeni.setText("Příjmení:");

        buttonOK.setText("OK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPrijmeni)
                    .addComponent(labelJmeno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldSurename))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(buttonOK)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJmeno)
                    .addComponent(textFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrijmeni)
                    .addComponent(textFieldSurename, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(buttonOK)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOK;
    private javax.swing.JLabel labelJmeno;
    private javax.swing.JLabel labelPrijmeni;
    private javax.swing.JTextField textFieldFirstName;
    private javax.swing.JTextField textFieldSurename;
    // End of variables declaration//GEN-END:variables
}
